../../bmp2vect -file:olipix1.bmp > olipix1.c 
../../bmp2vect -file:olipix1.bmp > olipix2.c 
../../bmp2vect -file:olipix1.bmp > olipix3.c 
../../bmp2vect -file:olipix1.bmp > olipix4.c 
../../bmp2vect -file:olipix1.bmp > olipix5.c 
../../bmp2vect -file:olipix1.bmp > olipix6.c 
../../bmp2vect -file:olipix1.bmp > olipix7.c 
../../bmp2vect -file:olipix1.bmp > olipix8.c 
../../bmp2vect -file:olipix1.bmp > olipix9.c 
../../bmp2vect -file:olipix1.bmp > olipix10.c 
../../bmp2vect -file:olipix1.bmp > olipix11.c 
../../bmp2vect -file:olipix1.bmp > olipix12.c 
../../bmp2vect -file:olipix1.bmp > olipix13.c 
../../bmp2vect -file:olipix1.bmp > olipix14.c 
../../bmp2vect -file:olipix1.bmp > olipix15.c 
../../bmp2vect -file:olipix1.bmp > olipix16.c 
../../bmp2vect -file:olipix1.bmp > olipix17.c 
../../bmp2vect -file:olipix1.bmp > olipix18.c
